### ISSUE TITLE
'OSError' object has no attribute 'message'

### ISSUE THREAD

**Issue by ehooo** [mattgwwalker/msg-extractor#112]
**Bug Metadata**
* Using latest supported version of extract_msg (version 0.23.3)
* Your python version: Python 3.6.9
* I used the extract_msg package

**Describe the bug**
AttributeError: 'OSError' object has no attribute 'message'
```python
from extract_msg import Message
Message(open('file.raw', 'rb'))
```

**Traceback**
```
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/extract_msg/message.py in __init__(self, path, prefix, attachmentClass, filename)
     44         try:
---> 45             olefile.OleFileIO.__init__(self, path)
     46         except IOError as e:    # py2 and py3 compatible

/usr/local/lib/python3.6/dist-packages/olefile/olefile.py in __init__(self, filename, raise_defects, write_mode, debug, path_encoding)
   1074         if filename:
-> 1075             self.open(filename, write_mode=write_mode)
   1076

/usr/local/lib/python3.6/dist-packages/olefile/olefile.py in open(self, filename, write_mode)
   1191             log.debug('Magic = %r instead of %r' % (header[:8], MAGIC))
-> 1192             self._raise_defect(DEFECT_FATAL, "not an OLE2 structured storage file")
   1193

/usr/local/lib/python3.6/dist-packages/olefile/olefile.py in _raise_defect(self, defect_level, message, exception_type)
   1104             log.error(message)
-> 1105             raise exception_type(message)
   1106         else:

OSError: not an OLE2 structured storage file

During handling of the above exception, another exception occurred:
```

**Comment by TheElementalOfCreation** [comment]
Please give us the error that happened during handling

**Comment by ehooo** [comment]
Sorry @TheElementalOfCreation i'm forget paste the last part of the traceback:
As you see the last line said: `During handling of the above exception, another exception occurred:`
```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/extract_msg/message.py", line 48, in __init__
    if e.message == 'not an OLE2 structured storage file':
AttributeError: 'OSError' object has no attribute 'message'
```

**Comment by ehooo** [comment]
I want make a test for that case.
Could you help me with it? i have the following error when i run: `python setup.py test`:
```
running egg_info
writing extract_msg.egg-info/PKG-INFO
writing dependency_links to extract_msg.egg-info/dependency_links.txt
writing requirements to extract_msg.egg-info/requires.txt
writing top-level names to extract_msg.egg-info/top_level.txt
file extract_msg.py (for module extract_msg) not found
reading manifest file 'extract_msg.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'README.md'
writing manifest file 'extract_msg.egg-info/SOURCES.txt'
running build_ext
test (unittest.loader._FailedTest) ... ERROR

======================================================================
ERROR: test (unittest.loader._FailedTest)
----------------------------------------------------------------------
AttributeError: module '__main__' has no attribute 'test'

----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (errors=1)
tests (unittest.loader._FailedTest) ... ERROR

======================================================================
ERROR: tests (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: tests
Traceback (most recent call last):
  File "/usr/lib/python3.7/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/home/ehooo/code/msg-extractor/tests.py", line 52, in <module>
    unittest.main(verbosity=2)
  File "/usr/lib/python3.7/unittest/main.py", line 101, in __init__
    self.runTests()
  File "/usr/lib/python3.7/unittest/main.py", line 273, in runTests
    sys.exit(not self.result.wasSuccessful())
SystemExit: True


----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (errors=1)
Test failed: <unittest.runner.TextTestResult run=1 errors=1 failures=0>
error: Test failed: <unittest.runner.TextTestResult run=1 errors=1 failures=0>
```

Thanks in advance

**Comment by TheElementalOfCreation** [comment]
Testing has not been setup

**Comment by ehooo** [comment]
Thank @TheElementalOfCreation I'm asking cause i see on the PR scheme.
Shall i create the PR? or must i update the CHANGELOG file?

**Comment by TheElementalOfCreation** [comment]
This will soon be fixed in an update we are releasing soon. The problem was that in Python 2, getting the message of an exception could be done by using `exception_var.message`, but this is no longer valid in Python 3. A method that does work in both versions is to call `str(exception_var)`, so we changed it.
