### ISSUE TITLE
Message.save fails when .__crlf undefined in v0.27.0

### ISSUE THREAD

**Issue by gregoryfoster** [mattgwwalker/msg-extractor#147]
**Bug Metadata**
* Version of extract_msg: 0.27.0
* Your python version: Python 3.8.3
* How did you launch extract_msg?
  - [ ] My command line or
  - [X] I used the extract_msg package

**Describe the bug**
See traceback for details, bug does not exist in 0.26.4 which I rolled back to.  Looks like `Message.save` fails if the message's `__crlf` attribute is not defined.

Is there a message.msg file you want to share to help us reproduce this?
- [X] Uploaded message (drag and drop on this window)
[423754  ZIPS CANNABIS.msg.zip](https://github.com/mattgwwalker/msg-extractor/files/5121292/423754.ZIPS.CANNABIS.msg.zip)

**Traceback**
```bash
Traceback (most recent call last):
  File "process.py", line 436, in <module>
    process()
  File ".venv/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File ".venv/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File ".venv/lib/python3.8/site-packages/click/core.py", line 1289, in invoke
    rv.append(sub_ctx.command.invoke(sub_ctx))
  File ".venv/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File ".venv/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File ".venv/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "process.py", line 332, in email
    msg.save(customPath=output_root, customFilename=label)
  File ".venv/lib/python3.8/site-packages/extract_msg/message.py", line 61, in save
    crlf = inputToBytes(self.__crlf, 'utf-8')
AttributeError: 'Message' object has no attribute '_Message__crlf'
```

**Comment by TheElementalOfDestruction** [comment]
This bug should be fixed. Please tell us if you run into any more issues.

**Comment by gregoryfoster** [comment]
Confirmed, looks good!  Thank you very much for the quick response!
