### ISSUE TITLE
Enable saving Appointments

### ISSUE THREAD

**Issue by gregoryfoster** [mattgwwalker/msg-extractor#149]
Building on #143, please implement saving of `IPM.Schedule.Meeting.Request` objects.

**Comment by gregoryfoster** [comment]
Traceback of current exception when attempting to save an `Appointment`:

```bash
Traceback (most recent call last):
  File "process.py", line 436, in <module>
    process()
  File ".venv/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File ".venv/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File ".venv/lib/python3.8/site-packages/click/core.py", line 1289, in invoke
    rv.append(sub_ctx.command.invoke(sub_ctx))
  File ".venv/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File ".venv/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File ".venv/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "process.py", line 332, in email
    msg.save(customPath=output_root, customFilename=label)
  File ".venv/lib/python3.8/site-packages/extract_msg/message.py", line 110, in save
    attachmentNames.append(attachment.save(ContentId, toJson, useFileName, raw, html = html, rtf = rtf))
  File ".venv/lib/python3.8/site-packages/extract_msg/attachment.py", line 230, in save
    self.saveEmbededMessage(contentId, json, useFileName, raw, customPath, customFilename, html, rtf)
  File ".venv/lib/python3.8/site-packages/extract_msg/attachment.py", line 239, in saveEmbededMessage
    self.data.save(json, useFileName, raw, contentId, customPath, customFilename, html, rtf)
  File ".venv/lib/python3.8/site-packages/extract_msg/msg.py", line 358, in save
    raise NotImplementedError('Saving is not yet supported for the {} class'.format(self.__class__.__name__))
NotImplementedError: Saving is not yet supported for the Appointment class
```

**Comment by gregoryfoster** [comment]
Example `.msg` and raw output captured when attempting to save:
[2020_04_08-14_19_38 RE  Industry WexEx (3).zip](https://github.com/mattgwwalker/msg-extractor/files/5125606/2020_04_08-14_19_38.RE.Industry.WexEx.3.zip)

**Comment by TheElementalOfDestruction** [comment]
I prioritized having a class that could at least read the appointment files rather than save them, and for good reason. The implementation took at least a week for the rest of the class, and I expect it to take at least another week just for saving it. Sorry, but this will take a bit.

**Comment by TheElementalOfDestruction** [comment]
So for saving I've hit a bit of a snag. The lists of attendees will sometimes just be completely blank, and so I've been trying to use logic to determine how to generate them (as the documentation is sparse, non-existent, or written in such a way that it is not easy to figure out). I found one structure that definitely contains some of the attendees, but unfortunately the documentation on how to read the structure does not seem to match what I am seeing. When I follow the instructions to read the structure, I get a bunch of gibberish and bad data. I'm trying to look for examples (even in other languages) of this structure being parsed but am having a lot of trouble.

As such, I am at a bit of an impasse. I could either just pump out a quick save function that is bad and doesn't give out all of the data and call it "good enough" or I can wait until I get this working fully to put out a good save function. On the one hand, you have something you can use that doesn't fully work, but on the other you have nothing. I'm just not sure what to do at this point.

Sorry this is taking so long. I'm currently the only one working on this project, and as such may be suffering from the problem of having only one set of eyes to look at a problem with. I felt you deserved to know what was going on.

**Comment by TheElementalOfDestruction** [comment]
I'll see about uploading the code I have now in the hopes that someone might take a look at it and be able to figure out what is going wrong.

**Comment by gregoryfoster** [comment]
Thanks, @TheElementalOfDestruction, for your work on this issue.  If you can upload what you have working/saving as a separate branch, I'd be happy to take a look.

**Comment by TheElementalOfDestruction** [comment]
I'll upload what I have to a new branch at some point. I've isolated it to a file that can be directly imported and you can push the data to that. For now I've uploaded the isolated file to this comment. The stream in appointments you are looking to pass to the main class is `__substg1.0_805D0102`. The class to pass it to is `AppointmentUnsendableRecipients`.
[newDataEntries.zip](https://github.com/TeamMsgExtractor/msg-extractor/files/6078821/newDataEntries.zip)

**Comment by TheElementalOfDestruction** [comment]
FYI the problem I am having is that the `RecipientRow` structure (which only parses some of the data so far as it is not finished) is not correctly parsing the data is receives based on what I am seeing if I look at the raw data. I even tried to manually shift the location of the data start point until it would parse *any* of them correctly, but all of them failed.

**Comment by TheElementalOfDestruction** [comment]
I decided to just say screw it to the structure in the end, and am basically ignoring it. If you end up with a file that has it, then support can be added for it. Currently the code for 0.35.0 on next-release has full saving support for this class type. I'm just finishing up a few more things before releasing it.
