### ISSUE TITLE
NameError: name 'getcwd' is not defined

### ISSUE THREAD

**Issue by mishmenez** [mattgwwalker/msg-extractor#76]
Traceback (most recent call last):
  File "parse_msg.py", line 2, in <module>
    import extract_msg
  File "/usr/local/lib/python3.4/dist-packages/extract_msg/__init__.py", line 34, in <module>
    from extract_msg.attachment import Attachment
  File "/usr/local/lib/python3.4/dist-packages/extract_msg/attachment.py", line 6, in <module>
    from extract_msg.properties import Properties
  File "/usr/local/lib/python3.4/dist-packages/extract_msg/properties.py", line 5, in <module>
    from extract_msg.prop import create_prop
  File "/usr/local/lib/python3.4/dist-packages/extract_msg/prop.py", line 4, in <module>
    from extract_msg.utils import properHex
  File "/usr/local/lib/python3.4/dist-packages/extract_msg/utils.py", line 15, in <module>
    from extract_msg.compat import os_ as os
  File "/usr/local/lib/python3.4/dist-packages/extract_msg/compat/os_.py", line 9, in <module>
    getcwdu = getcwd
NameError: name 'getcwd' is not defined

**Comment by TheElementalOfCreation** [comment]
Please open a python terminal and run the following:

```
import os
os.getcwd
```

And please report if this raises any errors

**Comment by mishmenez** [comment]
Hi Sir,

import os
os.getcwd

This works fine

The error is only at the below import:

import extract_msg

**Comment by TheElementalOfCreation** [comment]
Given that this:
```
"""
Compatibility module to ensure that certain functions exist across python versions
"""

from os import *
import sys

if sys.version_info[0] >= 3:
    getcwdu = getcwd
```
Is the file that is causing the error, I suggest you try reinstalling the module and see if that fixes the problem.

**Comment by mishmenez** [comment]
Reinstalling dint solve the issue either.
Any alternative to the problem statement: Parse .msg (Outlook emails) in python on ubuntu

**Comment by TheElementalOfCreation** [comment]
AFIK the problem is with your installation. Try running this command in your terminal before reinstalling the module:
```
rm -R /usr/local/lib/python3.4/dist-packages/extract_msg
```
(I always forget whether recursive is a capital or lowercase r. If it is not the capital R, correct the command to reflect that)

**Comment by TheElementalOfCreation** [comment]
Also, none of us have been able to replicate this issue.
